---
abstract: unknown
author:
  - 'Slaven Rezic <srezic@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Acme-Study-SREZIC
no_index:
  directory:
    - t
    - inc
requires:
  GD: 0
  Test::More: 0
  XML::LibXML: 0
resources:
  repository: git://github.com/eserte/acme-study-srezic.git
version: 1.00
